### ISSUE TITLE
Cannot read a table with a byte field

### ISSUE THREAD

**Issue by ellis2323** [andipaetzold/mdb-reader#218]
I'm trying to read the table tRelais in this mdb:
https://u.pcloud.link/publink/show?code=XZu5EHVZVqot9BBBU7FMwQHIVSJ4zHIwB9i7

If I read this table with "sysinfotool MDB file viewer 20.0", I read a full table with no empty data. But, if I read with this library, I found many empty object:
```
{NoEngageRelais: 1487, NoEngagement: 44242, NoSerieTour: 8096, NoAthlete: 13310, NoOrdreRelais: null}
{NoEngageRelais: 1488, NoEngagement: 44242, NoSerieTour: 8096, NoAthlete: null, NoOrdreRelais: null} ...
```

The field NoOrdreRelais has the type `octet` in french language... It is a small int with 8bits.

My script:
```
function loadRelais (reader) {
  let cmtrelays = new Map()
  const table = reader.getTable('tRelais')
  let rows = table.getData()
  for (let row of rows) {
    console.log(row)
    let uid = row.NoEngageRelais
    let noEngagement = row.NoEngagement
    let serieTour = row.NoSerieTour
    let athUID = row.NoAthlete
    let ord = row.NoOrdreRelais
    cmtrelays.set(uid, { uid, noEngagement, serieTour, athUID, ord })
  }
  return cmtrelays
}
```

**Comment by andipaetzold** [comment]
:wave: Hello again,

I was able to reproduce the issue. The problem seems to be that that row thinks it has more variable columns than total columns.
How was this table created? Was there a lot of altering and moving of the columns? Are you able to reproduce such broken table from scratch?

I'll hope I find time next week to investigate this further. There seems to be a related issue when only a subset of columns is read...

**Comment by ellis2323** [comment]
Hello,

This table is created by an access application developed by a french company 20 years ago and maintained until now. When you say "only a subset of columns is read", which alternative is available ?

**Comment by andipaetzold** [comment]
> 20 years ago and maintained until now.

Yeah, I noticed that. Can't even open the file in a current Microsoft Access :(

>  When you say "only a subset of columns is read", which alternative is available ?

This is probably unrelated to your problem. It might lead to the same result (`null` values), but when calling `getData()` with a `columns` option. I need to do more investigation around this.

I don't see any workaround at the moment.

**Comment by ellis2323** [comment]
I've a computer with XP and Access97. This table is the one with this **short int**. Are you sure this type of data is well read ?

**Comment by andipaetzold** [comment]
Yes, the column definitions are read correctly. If not, you would get `null` everywhere.

The issue is that `fixedColumnCount` becomes a negative number (https://github.com/andipaetzold/mdb-reader/blob/a9847d67ec2033b3cc8cdd0f61004d95e917dbda/src/Table.ts#L318) because `variableColumnCount` is greater than `totalVariableCount`. If that happens, we end up in the else branch (https://github.com/andipaetzold/mdb-reader/blob/a9847d67ec2033b3cc8cdd0f61004d95e917dbda/src/Table.ts#L350-L352) when reading the row and the value becomes `null`.

**Comment by ellis2323** [comment]
Hello,

When i read this table, I miss 1 column (NoOrdreRelais) for the first row, then I miss two columns (NoAthlete, NoOrdreRelais), then 3 columns (NoSerieTour, NoAthlete, NoOrdreRelais), then 4 columns and then it loop again with one column missing, then two.... The written values are correct. 

relais {
  NoEngageRelais: 228,
  NoEngagement: 1222,
  NoSerieTour: 444,
  NoAthlete: 666,
  NoOrdreRelais: null
}
relais {
  NoEngageRelais: 229,
  NoEngagement: 1222,
  NoSerieTour: 444,
  NoAthlete: null,
  NoOrdreRelais: null
}
relais {
  NoEngageRelais: 230,
  NoEngagement: 1222,
  NoSerieTour: null,
  NoAthlete: null,
  NoOrdreRelais: null
}
relais {
  NoEngageRelais: 231,
  NoEngagement: null,
  NoSerieTour: null,
  NoAthlete: null,
  NoOrdreRelais: null
}

**Comment by ellis2323** [comment]
The table in Access97 have 5 fields:

 * NoEngageRelais: AutoNumber
 * NoEngagement: Numeric
 * NoSerieTour: Numeric
 * NoAthlete: Numeric
 * NoOrdreRelais: Numeric

All columns are defined and set.

**Comment by andipaetzold** [comment]
I think I found the issue. Seems like this was just a small mistake in the Jet3 format configuration.
The new version should release any minute. Please let me know if you still run into issues with the latest update.

**Comment by ellis2323** [comment]
Hello,

I tried this morning and everything is ok. Good job.

Thanks for your great work.
