### ISSUE TITLE
Can't Import it

### ISSUE THREAD

**Issue by iamadityaaz** [andipaetzold/mdb-reader#237]
I am unable to use `const MDBParser = require("mdb-reader")`. I don't wanna change all other imports of other libraries being used.

**Comment by andipaetzold** [comment]
Hey,

I dropped support for commonJS with version 2. This library is now a pure ESM package and I currently do not have plans to reintroduce CJS support.

Instead of using v1, you could also transpile the package to commonJS yourself.

Check out this gist by Sindre about pure ESM packages: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
